### ISSUE TITLE
Support aiohttp 1.1

### ISSUE THREAD

**Issue by IlyaSemenov** [samuelcolvin/aiohttp_runserver#2]
The current version doesn't work with aiohttp 1.1:

```console
$ arun
Traceback (most recent call last):
  File "/Users/semenov/.pyenv/versions/test/bin/arun", line 7, in <module>
    from aiohttp_runserver.main import cli
  File "/Users/semenov/.pyenv/versions/3.5.2/envs/test/lib/python3.5/site-packages/aiohttp_runserver/main.py", line 10, in <module>
    from .serve import create_auxiliary_app, import_string
  File "/Users/semenov/.pyenv/versions/3.5.2/envs/test/lib/python3.5/site-packages/aiohttp_runserver/serve.py", line 12, in <module>
    from aiohttp.web_urldispatcher import StaticRoute
ImportError: cannot import name 'StaticRoute'
```

There's no `StaticRoute`, only `StaticResource` at `aiohttp.web_urldispatcher`.

...or if the project is abandoned, please leave a note in the header. Thanks.

**Comment by samuelcolvin** [comment]
Please use https://github.com/samuelcolvin/aiohttp-devtools it has the same functionality in the `runserver` command and is in active development.

**Comment by samuelcolvin** [comment]
I'll update the README
